POST https://academia-database.onrender.com/market
Content-Type: application/json

{
    "image": "https://nutrata.com.br/wp-content/uploads/2022/05/whey-grego-bar-sabor-dulce-de-leche-havanna-display-c-12-barras-de-40-gr.png.webp",
    "title": "Whey Grego Bar sabor Dulce de Leche HAVANNA display c/ 12 barras de 40 gr",
    "rate" : 5,
    "cost": "111,86",
    "description": "A melhor barra de proteína eleita pelos consumidores combinada a tradição do dulce de leche argentino da Havanna"
}

###

GET https://academia-database.onrender.com/market

###

PUT https://academia-database.onrender.com/market/:d0cf6741-f54f-49f4-b2bc-4541910f3e6e
Content-Type: application/json

{
    "image": "https://nutrata.com.br/wp-content/uploads/2022/05/whey-grego-bar-sabor-dulce-de-leche-havanna-display-c-12-barras-de-40-gr.png.webp",
    "title": "dwwadadwadwadaway c/ 12 barras de 40 gr",
    "rate" : 5,
    "cost": "111,86",
    "description": "A melhor barra de proteína eleita pelos consumidores combinada a tradição do dulce de leche argentino da Havanna, uma das escolhas mais saborosas para se experimentar."
}

###

DELETE https://academia-database.onrender.com/market/3d4c61fe-a42e-4adc-a724-d821ab894f17